name: Deploy to Test Server

on:
  workflow_run:
    workflows:
      - 'Build WAR'
    types:
      - completed

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download built WAR
        uses: actions/download-artifact@v4
        with:
          name: war-file
          pr: ${{ github.event.pull_request.number }}

      - name: Rsync WAR to Test Server
        uses: burnett01/rsync-deployments@7.1.0
        with:
          remote_host: ${{ secrets.TEST_SERVER_HOST }}
          remote_user: ${{ secrets.TEST_SERVER_USERNAME }}
          remote_key: ${{ secrets.TEST_SERVER_KEY }}
          path: HealthNutrition.war
          remote_path: /tmp/

      - name: Install WAR on Test Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          key: ${{ secrets.TEST_SERVER_KEY }}
          script: /root/tomcat/HealthNutrition/deploy.sh
